linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
  disable:
    - typecheck

linters-settings:
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G104 # Errors unhandled
      - G107 # Url provided to HTTP request as taint input
      - G402 # TLS InsecureSkipVerify set true

run:
  skip-dirs:
    - vendor
    - testdata
    - third_party
    - internal
    - /usr/local/go/src
    - /go/pkg/mod

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: .*\.go
      linters:
        - typecheck
