linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
  disable:
    - typecheck # Disable typecheck as it's causing false positives

linters-settings:
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G104 # Errors unhandled
      - G107 # Url provided to HTTP request as taint input
      - G402 # TLS InsecureSkipVerify set true

run:
  skip-dirs:
    - vendor
    - testdata
    - .git
    - .github
    - bin
    - tmp
    - /usr/local/go/src # Exclude standard library
    - /home/kiro123/go/pkg/mod # Exclude all Go modules
    - /go/pkg/mod # Alternative path for Go modules

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: auth/auth\.go
      linters:
        - typecheck
    - path: auth/email\.go
      linters:
        - typecheck
    - path: middleware/rate_limit\.go
      linters:
        - typecheck
    - path: test/mocks/db\.go
      linters:
        - typecheck
    - path: handlers/test_helpers\.go
      linters:
        - typecheck
    - path: .*\.pb\.go$ # Exclude protobuf generated files
      linters:
        - typecheck
    - path: .*\.pb\.gw\.go$ # Exclude protobuf gateway generated files
      linters:
        - typecheck
